VAMSProject/VAMSProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from newapp import views
import json

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.home_view),
    url(r'^$', views.home_view),
    url(r'^search/$',views.search),
    path('cardholder/', views.cardholder_view),
    path('livemonitoring/',views.show),
    path('create/', views.create),
    path('report/', views.Employee_info_view),
    path('show/',views.show),
    path('emp',views.emp),
    path('edit/<int:id>',views.edit),
    path('update/<int:id>',views.update),
    path('delete/<int:id>',views.delete),
    path('json_data/', views.emp_view_json),
]

VAMSProject/newapp/models.py
from django.db import models

class Employee12(models.Model):
    eid= models.CharField(max_length=15)
    ecard= models.IntegerField()
    efname = models.CharField(max_length=64)
    elname = models.CharField(max_length=64)
    eagency = models.CharField(max_length=64)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table = "Employee12"

VAMSProject/newapp/views.py
from django.shortcuts import render, redirect, HttpResponse
from newapp import views
from newapp.form import EmployeeForm
from newapp.models import Employee12
from django.db.models import Q
import json
# Create your views here.


def home_view(request):

    return render(request,'newapp/home.html')

def cardholder_view(request):

    return render(request,'newapp/cardholder.html')

def Employee_info_view(request):

    return render(request,'newapp/results.html')

def create(request):
    return render(request,'newapp/show.html')

# This code create Employee data and after that it show all employee.
def emp(request):
    form = EmployeeForm
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                #if(form.checkIfRecordExist()==false):
                    form.save()
                    return redirect("/show")
                #else:
                    #message.render('Record alredy exist..!!')

            except:
                pass
        else:
            form = EmployeeForm()
    return render(request,'newapp/index.html',{'form':form})

#checkIfRecordExist



def show(request):
    employees = Employee12.objects.all()
    return render(request,'newapp/show.html',{'employees':employees})
#below code for edit employee data.
def edit(request,id):
    employee = Employee12.objects.get(id=id)
    return render(request,"newapp/edit.html",{'employee':employee})
#Below code for update and redirect show page.
def update(request,id):
    employee =Employee12.objects.get(id=id)
    form=EmployeeForm(request.POST,instance=employee)

    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request,"newapp/edit.html",{'employee12':employee})
#below code for delete id.
def delete(request,id):
    employee = Employee12.objects.get(id=id)
    employee.delete()
    return redirect("/show")
# Below code for search key.
def search(request):
    if request.method == 'POST':
        srch = request.POST['srh']
        if srch:
            match = Employee12.objects.filter(Q(eid__icontains=srch) | Q(efname__icontains=srch) |
            Q(elname__icontains=srch))
            if match:
                return render (request,'newapp/cardholder.html',{'sr':match})
            else:
                messages.error(request,'no result found')
        else:
            return HttpResponseRedirect('/search')
    return render(request,'newapp/cardholder.html')

        #id = request.POST.get('id')
        #card = request.POST.get('card')
        #firstname = request.POST.get('firstname')
        #lastname = request.POST.get('lastname')
        #agency = request.POST.get('agency')
    #return render(request,'testapp/create_new.html')

#def results_view(request):
    #if request.method == "POST":
        #name = request.POST['card','id','firstname','lastname','agency']
        #print(name)

    #return render(request,'testapp/result.html')
import json
def emp_view_json(request):
    emp_data={
    'eno':100,
    'ename':'Almas',
    'esal':20000,
    }
    json_data=json.dumps(emp_data)
    return HttpResponse(json_data,content_type='application/json')

VAMSProject/newapp/templates/newapp/basic.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <h1>Hello world</h1>
  </body>
  <h2> Hello Django</h2>
</html>

VAMSProject/newapp/templates/newapp/cardholder.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
body {
  background-color: silver;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
*{
 box-sizing : border-box;
}

form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}
form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}
.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}


.topnav a.vams {
  background-color: #00FF00;
  color: white;
}
h2{color:black;
  text-align:left;
}
p{color:blue;
  text-align:left;
}

</style>
</head>
<body>

<div class="topnav">

  <a class="vams" href="#vams">VAMS.NET</a>
  <a class="active" href="/test">Home</a>
  <a href="#news">Configuration</a>
  <a href="/emp">Card Holder</a>
  <a href="/report">Report</a>
  <a href="#contact">Active Reader</a>
  <a href="/livemonitoring">Live Monitoring</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
</div>

<div style="font-size:30px;">
  <h2>Index</h2>
  <a href="/emp">Create New</a>
</div>
<! _____search Box______ >
<div class="container">

<form method="post" action="/search/" class="example" style="margin:auto;max-width:500px">
  {% csrf_token%}
  <h3>Smart search</h3>
  <div class="col-lg-5">
  <input type="text" name="srh" class="form-control" placeholder="Search..">
</div>
<label class="col-lg-2">
  <button type="submit" class="btn.btn-danger"><i class="fa fa-search"></i></button>
</label>
</div>
</form><br><br>
<div>
{% if messages %}
<ul class="messages">
  {% for k in messages %}
  <li style="color: red">{{k}}</li>
  {% endfor%}
</ul>
{% endif %}
</div>
<br>
<div style="color: blue">
{% if sr %}
  {% for k in sr %}
<table border="1px" width="300px">
  <tr>
    <th>Employee ID</th>
<th>Employee Card Number</th>
<th>Employee First Name</th>
<th>Employee Last Name</th>
<th>Employee Agency</th>
<th>Employee Email</th>
<th>Employee Contact</th>
<th>Actions</th>
</tr>
<tboday>

    <tr>
        <td>{{k.eid}}</td>
        <td>{{k.ecard}}</td>
        <td>{{k.efname}}</td>
        <td>{{k.elname}}</td>
        <td>{{k.eagency}}</td>
        <td>{{k.eemail}}</td>
        <td>{{k.econtact}}</td>
      <td><a href="/edit/{{employee.id}}" class="button">Edit</a>
      <a href="/delete/{{employee.id}}" class="button">Delete</a></td>
    </tr>
  </table>
     <hr>
   {% endfor %}
 {% endif %}
</div>
</div>

</body>

</html>

VAMSProject/newapp/templates/newapp/create_new.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
  body {
    margin: 70px;
    font-family: Arial;
    font-size:
    }
    form{
      padding: 10px;
      font-size: 17px;
      border: 1px solid grey;
      float: left;
      width: 80%;
      background: #f1f1f1;
}
</style>
</head>
<body>
<h2>Fill employee details</h2>
<div>
      <form method="post" class="post-form" action="/create_view">
        {% csrf_token %}
  Card Number:<br>
  <input type="text" card="card"  size="50">
  <br>
  Id:<br>
  <input type="text" id="id"  size="50">
<br>
  First name:<br>
  <input type="text" firstname="firstname"  size="50">
  <br>
  Last name:<br>
  <input type="text" lastname="lastname"  size="50">
  <br>
  Agency:<br>
  <input type="text" agency="agency"  size="50">
  <br>
  <br><br>
  <input type="submit" value="Submit">
</form>
</div>
<p></p>
</body>
</html>

VAMSProject/newapp/templates/newapp/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Edit</title>
    {%load staticfiles%}
    <link rel="stylesheet" href="{% static '/style.css'%}"/>
    <style>
body {
  background-color: lightblue;
}



h1 {
  font-family: verdana;
  font-size: 20px;
  text-align: center;
}
</style>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
    {%csrf_token%}
    <div class="container">
        <br>
        <div class="form-group row">
        <label class="col-sm-1 col form-label"></label>
            <div class="col-sm-4">
                <h3>Update Details</h3>
            </div>
         </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Employee Id: </label>
            <div class="col-sm-4">
                <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{employee.eid}}"/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Employee Card: </label>
            <div class="col-sm-4">
                <input type="text" name="ecard" id="id_ecard" required maxlength="20" value="{{employee.ecard}}"/>
            </div>
        </div>

         <div class="form-group row">
            <label class="col-sm-2 col-form-label">Employee Farst Name: </label>
            <div class="col-sm-4">
                <input type="text" name="efname" id="id_efname" required maxlength="100" value="{{employee.efname}}"/>
            </div>
        </div>

        <div class="form-group row">
           <label class="col-sm-2 col-form-label">Employee Last Name: </label>
           <div class="col-sm-4">
               <input type="text" name="elname" id="id_elname" required maxlength="100" value="{{employee.elname}}"/>
           </div>
       </div>

       <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Agency: </label>
          <div class="col-sm-4">
              <input type="text" name="eagency" id="id_eagency" required maxlength="100" value="{{employee.eagency}}"/>
          </div>
      </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Employee Email: </label>
            <div class="col-sm-4">
                <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{employee.eemail}}"/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Employee Contact: </label>
            <div class="col-sm-4">
                <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{employee.econtact}}"/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>



</form>

</body>
</html>

VAMSProject/newapp/templates/newapp/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}


.topnav a.vams {
  background-color: #00FF00;
  color: white;
}
h2{color:red;
  text-align:center;
}
p{color:blue;
  text-align:center;

}
</style>
</head>
<body>

<div class="topnav">
<div class="container">


  <a class="vams" href="#vams">VAMS.NET</a>
  <a href="/home">Home</a>
  <a href="#news">Configuration</a>
  <a href="/cardholder">Card Holder</a>
  <a href="/report">Report</a>
  <a href="#contact">Active Reader</a>
  <a href="/livemonitoring">Live Monitoring</a>
  <a href="#contact">Contact</a>
  <a href="#">About</a>
  </div>
</div>

<div style="font-size:30px;">
  <h2>Vendor Attendance Management System</h2>
  <p>Easy way To Create And Manage Your Vendor Access Management System</p>
  <img src="{% static "Images/1234.jpg"%}">
</div>

</body>
</html>

VAMSProject/newapp/templates/newapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/style.css'%}"/>
    <style>
body {
  background-color: lightblue;
}



h1 {
  font-family: verdana;
  font-size: 20px;
  text-align: center;
}
</style>
</head>
<body>
<form method="POST" class="post-form" action="/emp">
    {%csrf_token%}
    <div class="container">
        <br>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter Details</h3>
            </div>
            <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
            <div class="col-sm-4">
                {{form.eid}}
            </div>
            <div class="form-group row">
      <label class="col-sm-2 col-form-label">Employee Card:</label>
          <div class="col-sm-4">
              {{form.ecard}}
          </div>
            </div>
            <div class="form-group row">
      <label class="col-sm-2 col-form-label">Employee First Name:</label>
          <div class="col-sm-4">
              {{form.efname}}
          </div>
            </div>
              <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Last Name:</label>
            <div class="col-sm-4">
                {{form.elname}}
            </div>
              </div>
              <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Agency:</label>
            <div class="col-sm-4">
                {{form.eagency}}
            </div>
              </div>
          <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
            <div class="col-sm-4">
                {{form.eemail}}
            </div>
          </div>

          <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
            <div class="col-sm-4">
                {{form.econtact}}
            </div>
          </div>
                 <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
         <button type="submit" class="btn btn-primary">Submit</button>
            </div>
    </div>
</form>
</body>
</html>

VAMSProject/newapp/templates/newapp/results.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Employees Informations</h1>
    {% if Employees %}
    <table border=2>
      <thead>

      <th>Employee Idn</th>
      <th>Employee Card Number</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Agency</th>
      </thead>
      {% for emp in Employees %}
      <tr>
        <td>{{emp.id}}</td>
        <td>{{emp.card}}</td>
        <td>{{emp.fname}}</td>
        <td>{{emp.lname}}</td>
        <td>{{emp.agency}}</td>
      </tr>
      {%endfor%}
    </table>
    {%else%}
    <p>No Employee Record Found !!!</p>
    {%endif%}
  </body>
</html>

VAMSProject/newapp/templates/newapp/search.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
*{
 box-sizing : border-box;
}

form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}
form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}
.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}


.topnav a.vams {
  background-color: #00FF00;
  color: white;
}
h2{color:black;
  text-align:left;
}
p{color:blue;
  text-align:left;
}

</style>
</head>
<body>

<div class="topnav">

  <a class="vams" href="#vams">VAMS.NET</a>
  <a class="active" href="/test">Home</a>
  <a href="#news">Configuration</a>
  <a href="/emp">Card Holder</a>
  <a href="/report">Report</a>
  <a href="#contact">Active Reader</a>
  <a href="/livemonitoring">Live Monitoring</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
</div>

<div style="font-size:30px;">
  <h2>Index</h2>
  <a href="/emp">Create New</a>
</div>
<! _____search Box______ >
<div>

<form class="example" action="/action_page.php" style="margin:auto;max-width:500px">
  <h3>Smart search</h3>
  <input type="text" placeholder="Search.." name="search2">
  <button type="submit"><i class="fa fa-search"></i></button>
  <br>
  <hr>

</form>
</div>
<br>


</body>

</html>

VAMSProject/newapp/templates/newapp/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Record</title>
    {%load staticfiles%}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!__link rel="stylesheet" href="{% static '/style.css'%}"/__>
    <style>

    body{
          background-color: silver;
        }

    form.example input[type=text] {
      padding: 10px;
      font-size: 17px;
      border: 1px solid grey;
      float: left;
      width: 80%;
      background: #f1f1f1;
    }
    form.example button{
      float: left;
      width: 20%;
      padding: 10px;
      background: #2196F3;
      color: white;
      font-size: 17px;
      border: 1px solid grey;
      border-left: none;
      cursor: pointer;
    }
    .topnav {
      overflow: hidden;
      background-color: #333;
    }

    .topnav a {
      float: left;
      color: #f2f2f2;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }

    .topnav a:hover {
      background-color: #ddd;
      color: black;
    }


    .topnav a.vams {
      background-color: #00FF00;
      color: white;
    }




h1 {
  font-family: verdana;
  font-size: 20px;
  text-align: center;
}
.button {
  background-color: #008CBA;
  border: none;
  color: white;
  padding: 6px 12px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 2px 1px;
  cursor: pointer;
}
button1{
  background-color: lightblue;
  color: white;
  padding: 7px 15px;
  text-align: center;
  font-size: 20px;
}
</style>

</head>
<body>
  <div class="topnav">

    <a href="#vams" class="vams" >VAMS.NET</a>
    <a href="/test" >Home</a>
    <a href="#news" >Configuration</a>
    <a href="/emp" >Card Holder</a>
    <a href="/report" >Report</a>
    <a href="#contact" >Active Reader</a>
    <a href="/livemonitoring" >Live Monitoring</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
  </div>
  <! __Employee details>
  <h1>Employees Details</h1>

<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
    <th>Employee Card Number</th>
    <th>Employee First Name</th>
    <th>Employee Last Name</th>
    <th>Employee Agency</th>
    <th>Employee Email</th>
    <th>Employee Contact</th>
    <th>Actions</th>
    </tr>
    <tboday>
        {% for employee in employees %}
        <tr>
            <td>{{employee.eid}}</td>
            <td>{{employee.ecard}}</td>
            <td>{{employee.efname}}</td>
            <td>{{employee.elname}}</td>
            <td>{{employee.eagency}}</td>
            <td>{{employee.eemail}}</td>
            <td>{{employee.econtact}}</td>
            <td><a href="/edit/{{employee.id}}" class="button">Edit</span></a>
            <a href="/delete/{{employee.id}}" class="button">Delete</a></td>

        </tr>
        {% endfor %}
    </tboday>
    </table>

<br>
<br>
<center><a href="/emp" class="button button1">
  <span></span>
  <span></span>
  <span></span>
  <span></span>
  Add New Record</a> </center>
</body>
</html>